# Generated by Django 5.0 on 2024-02-07 14:41

import django.db.models.deletion
import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='status',
            field=models.ForeignKey(default=reports.models.status_pending, on_delete=django.db.models.deletion.SET_DEFAULT, to='reports.userreportstatus'),
        ),
    ]
