# Generated by Django 5.0 on 2024-02-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_userreport_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreportstatus',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
