# Generated by Django 5.0 on 2024-02-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_userreportstatus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='reported_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reported_object_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'beverage'), (2, 'brand')], null=True),
        ),
    ]
