# Generated by Django 5.0 on 2023-12-31 22:35

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    dependencies = [
        ("beverages", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
    ]
