# Generated by Django 5.0 on 2023-12-31 22:37

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0002_add_trigram_extension'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='beverage',
            index=django.contrib.postgres.indexes.GistIndex(fields=['name'], name='beverage_name_index', opclasses=['gist_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=django.contrib.postgres.indexes.GistIndex(fields=['name'], name='brand_name_index', opclasses=['gist_trgm_ops']),
        ),
    ]
