# Generated by Django 5.0 on 2024-01-01 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0003_beverage_beverage_name_index_brand_brand_name_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='abv',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'Non-alcoholic beers are allowed.'), django.core.validators.MaxValueValidator(99, "ABV cannot be higher than 99%, although realistically, it shouldn't be higher than ~20%.")]),
        ),
    ]
