# Generated by Django 5.0 on 2024-01-12 17:12

import django.db.models.deletion
import drink_log.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beverages', '0005_beverage_added_by_brand_added_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Volume (mL)')),
                ('timestamp', drink_log.fields.DateTimeWithoutTimeZoneField()),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverages.beverage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
