# Generated by Django 5.0 on 2024-01-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drink_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinklog',
            options={'verbose_name_plural': 'Drink log'},
        ),
    ]
