#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python manage.py collectstatic --no-input --clear

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/app